### ISSUE TITLE
Add a Flask app example for python

### ISSUE THREAD

**Issue by khalido** [zeit/now-examples#163]
I was trying to figure out how to run a flask app to setup up a simple API which can handle getting a call, then does some processing and returns say a string of text.

Is it possible to add a python example using flask (or similar) web framework to receive and serve requests?

**Comment by rauchg** [comment]
Yes. @liudonghua123 submitted a Flask builder: https://github.com/zeit/now-builders/pull/26

And @simonw has some thoughts on how to leverage ACGI / WCGI to reduce the need for even having a server to begin with!

**Comment by khalido** [comment]
Thanks for the quick reply. I looked at the flask builder - it looks complex! I don't quite grasp what all is going on there.

All the Zeit examples at https://zeit.co/docs/v2/deployments/builds/ are very nicely documented.

I agree a flask sever might be overkill, so I'll look into a simpler alternative.

In the python example here: https://zeit.co/docs/v2/deployments/official-builders/python-now-python/

its running pythons http.server - should I just use that to serve up api requests? I wanted to keep things simple as possible.

**Comment by liudonghua123** [comment]
@khalido
Acturally, it does not complex at all, all you need is to write three files, `index.py`, `requirements.txt`, `now.json`, You should write `now.json` as the following because the https://github.com/zeit/now-builders/pull/26 have not merged. Once it merged, you can replace `@liudonghua123/now-flask` with `now-flask` or something like.
```
{
  "version": 2,
  "builds": [
    { "src": "*.py", "use": "@liudonghua123/now-flask" }
  ]
}
```

I also write two simple examples, you can find on https://github.com/zeit/now-builders/pull/26/commits/3bdb547f692c1c8d60b58ed8738068d0a82333bd and https://github.com/zeit/now-builders/pull/26/commits/85225e6e3a075ec4eb49fff31e7210cea86a6985.

**Comment by khalido** [comment]
Thanks, that was very useful! I can now serve up a basic flask app, but I'm still having an issue with defining more routes:

The basic route works:

```
@app.route('/')
def hello_world():
    message = cow.Cowacter().milk('Hello from Python on Now Lambda!1111111') 
    return message
```

This doesn't work:
```
@app.route('/test')
def test_msg():
    message = "This is a test message"
    return message
```

I tried changing the ports etc, which doesn't seem to make a different as the / route is exposed on the web.

**Comment by liudonghua123** [comment]
@khalido You need to write a `route` like the following, more details can be found on https://zeit.co/docs/v2/deployments/configuration#routes
```
  "routes": [
    { "src": "/.*", "dest": "/"}
  ]
```

After adding this line, my https://github.com/zeit/now-builders/commit/85225e6e3a075ec4eb49fff31e7210cea86a6985 example can handle extra path request.

![image](https://user-images.githubusercontent.com/2276718/48826788-5323a880-eda6-11e8-8d4f-92fbb339af78.png)

**Comment by visini** [comment]
@khalido maybe this helps – it's a simple API example on python (not flask though): https://medium.com/@camillovisini/barebone-serverless-python-json-api-on-zeit-now-b90187021fb7

**Comment by visini** [comment]
Hi @khalido see my updated full tutorial for Flask. Thanks to the flask builder by @liudonghua123 I got it working. Let me know if you have any questions. Thanks!

Barebone Serverless Flask REST API on Zeit Now
https://medium.com/@camillovisini/barebone-serverless-flask-rest-api-on-zeit-now-9c2fe979c25c

**Comment by khalido** [comment]
Thanks very much to all you all! I'm finding Zeit.co awesomely easy to use and deploy to, and this flask bit was the one thing I needed.

One thing I noticed, using `{ "src": "*.py", "use": "@liudonghua123/now-flask" }` as the builder slowed down the build times quite a bit. I understand flask is bigger than the default python thingamajig, but hopefully Zeit.co can figure out how to speed it up later.

@visini thanks for the tutorial. one thing I'd like to see more in your tutorial is an recommendation on how to define multiple routes for the zeit.co world. Is it better to have a separate python file for each route, or just define them in one?

**Comment by liudonghua123** [comment]
Hi @khalido, Thanks for trying this builder, One thing to note is that because the https://github.com/zeit/now-builders/pull/26 was not merged and published to the npm officially, so you can test it using my `@liudonghua123/now-flask` npm package.  As for your performance concern, I will try to improve it. 😃

**Comment by agriffis** [comment]
@khalido is your builder available on github?

**Comment by untitaker** [comment]
I would like to see a now builder that takes an arbitrary WSGI app and invokes it directly, instead of creating a new thread to spawn Flask's dev server on a new port and hitting that port with requests like @liudonghua123's. [Zappa](https://github.com/Miserlou/Zappa) already does this for AWS Lambda, and is very popular because of that.

But stepping back I don't quite understand why Zeit's current Python runtime uses the stuff in `http.server` considering every (synchronous) Python web framework out there uses WSGI as common interface. It seems that this discussion has already been had in https://github.com/zeit/now-builders/issues/27 though.

**Comment by rauchg** [comment]
@untitaker our goal is most certainly to expose WSGI and deprecate the current mode of how `@now/python` works (ideally in a backwards-compatible way)

**Comment by rauchg** [comment]
If someone wants to help land that PR, it would be most certainly merged expediently. The only difference is that we want to call it `@now/python` and make it a backwards-compatible change.

**Comment by honzajavorek** [comment]
There are currently several PRs addressing exactly that: https://github.com/zeit/now-builders/pull/14 (Kenneth's), https://github.com/zeit/now-builders/pull/26 (Flask-oriented), https://github.com/zeit/now-builders/pull/163 (WSGI by Romain Clement), https://github.com/zeit/now-builders/pull/95 (WSGI by Sigurd Spieckermann). The last mentioned, #95, should include changes from #163, and I believe it is the closest to getting merged.

It would be great if Zeit assists the PR authors a bit to get this initial phase of fixing the Python support off the plate. I believe once at least one of them is merged, the situation can calm down - other PRs adding WSGI can get closed, the Python support gets "stable" and usable for everyone, and improvements can get incremental, i.e. delivered in small easy-to-review PRs.

**Comment by untitaker** [comment]
As far as I understand `zeit/now-builders` is the set of official builders while `now-examples` is the community-maintained set. From the README of `zeit/now-builders`:

>This is the full list of official Builders provided by the ZEIT team.

I don't think merging builders from outside contributors into `now-builders` is sustainable if they end up unmaintained. It seems that Zeit is not willing to invest anything from their end into Python right now, so I assume that's how it would go.

**Comment by rauchg** [comment]
@untitaker some clarifications:
- Anyone is free to publish a builder to npm
- You don't necessarily have to use builders from the `@now/` namespace. Builders are just npm packages
- ZEIT is definitely interested in maintaining an official python builder, and there will be news about this soon

**Comment by khalido** [comment]
I'm glad there is some movement on the now python front. As a relative newbie to all this my two cents to making now@python easier to use is that I wished it worked out of the box nicely with flask (or some other WSGI front-end).

Ideally I'd like two python builders:

1. an event handler like aws lambda

where all I'm doing is writing an event handler sort of like aws lambda but minus all the clicking around, configuring and deciding and thinking aws always forces on the user.

```
def handle_incoming(event, context):
   # process stuff, connect to things, reads a db, whatever
    msg = "our awesome msg"
    return msg
```

I think this could cover a lot of use cases for now@python, and instead of every user spinning up a server and serving stuff all that is left up to zeit, which I assume would make things work better/faster/cheaper?

So when my now url is pinged, my func is invoked, does its thing, and returns an object or msg which the now@python big picture function returns back to the user or takes in an OK and goes back to sleep.

I don't know if this makes sense, but basically pls abstract away servers and serving! 

I don't want to `from http.server import BaseHTTPRequestHandler` for every simple now func.

2. flask support (for more complex stuff than a simple event handler)

Since pretty much every tutorial/book on python is using flask.

Flask support means I could easily deploy a web app built with [dash by plotly](https://medium.com/@plotlygraphs/introducing-dash-5ecf7191b503) - which is just running on top of flask.

**Comment by untitaker** [comment]
@styfle can we close this? It seems https://github.com/zeit/now-builders/pull/14 is a thing now

**Comment by styfle** [comment]
Closing since we have [WSGI support](https://zeit.co/blog/python-wsgi) in the `@now/python` Builder. This works with most Python web frameworks by simply assigning the `app` variable in your entry point `.py` file.

See the following examples for Flask:

- https://github.com/zeit/now-examples/tree/master/python-flask
- https://github.com/zeit/now-examples/tree/master/flaskex-postgresql
