### ISSUE TITLE
Missing HTTP POST example for Node.js lambdas

### ISSUE THREAD

**Issue by sk22** [zeit/now-examples#208]
The Node.js example (https://github.com/zeit/now-examples/tree/master/nodejs) is lacking an HTTP POST endpoint. It's clear for servers like Express, but you call using servers "not recommended", so I think providing an example for creating a POST endpoint works with Node lambdas.

**Comment by ewrogers** [comment]
Express/Koa are not *necessarily* servers unless you use their `.listen()` method. Using their HTTP request parsing and routing capabilities does not make them a server in the classical sense. And if you dare to try and implement everything using the Node `http` library, you're going to end up reinventing the wheel anyhow.

Unfortunately, all the examples I see only support a single method for a resource which is a bit unrealistic for most REST APIs.

I do like the idea of your folder/file structure mirroring your REST API endpoints, so I've tried to keep with that convention in my project. I also want endpoints to look RESTful (not using file extensions).

To accomplish this with Koa, I've brought in `koa`, `koa-bodyparser`, and `koa-router`.

Here's my `now.json`:
```
{
"version": 2,
  "routes": [{ "src": "/api/(.*)", "dest": "/api/$1" }],
  "builds": [{ "src": "api/**/*.js", "use": "@now/node" }]
}
```

And my project structure has `./api/accounts/index.js`:
```
const Koa = require('koa')
const bodyParser = require('koa-bodyparser')
const Router = require('koa-router')

const app = new Koa()
const router = new Router()

router.get('*', require('./list-accounts'))
router.post('*', bodyParser(), require('./create-account'))

app.use(router.routes())
app.use(router.allowedMethods())

module.exports = app.callback()
```

The two sub-routes are just exported Koa functions (`(ctx) => { ... }`) and you are free to inject conditional middleware as needed.

Again, I'm not exactly 100% enthused by this solution because I feel that having routing done in `now.json` **and** using `koa-router` seems smelly, but there's no real way otherwise from what I can tell.

**Comment by sk22** [comment]
I didn't know you could do `module.exports = app.callback()`. Thanks for the clarification!

**Comment by JesusCrow** [comment]
I tried to parse JSON without any libs but failed. I ended up using `body/json` package. It was good enough for the momment.
```js
const jsonBody = require("body/json");

module.exports = async function(req, res) {
  try {
    if (req.method !== 'POST') {
      res.statusCode = 400;
      res.setHeader("Content-Type", "text/html");
      return res.end(
        `<h1>Bad Request</h1><p>Only accepting POST request.</p>`
      );
    }

    jsonBody(req, res, async (err, body) => {
      if (err) {
        throw err;
      }
      const { someProperty } = body;
  
      if (!someProperty) {
        res.statusCode = 400;
        res.setHeader("Content-Type", "text/html");
        return res.end(
          `<h1>Bad Request</h1><p>Must provide 'someProperty' in body.</p>`
        );
      }

      res.statusCode = 200;
      res.setHeader("Content-Type", "text/html");
      res.end(`<h1>someProperty</h1><p>${JSON.stringify(someProperty)}</p>`);
    });
  } catch (e) {
    res.statusCode = 500;
    res.setHeader("Content-Type", "text/html");
    res.end("<h1>Server Error</h1><p>Sorry, there was a problem</p>");
    console.error(e.message);
  }
};
```
But this whole method looks too verbose to me. Would be nice to have something like Express builder. Or maybe showing some functional composition examples of how users could use existing libraries/middlewares to chain existing packages for "simple" usage.

**Comment by maxbeatty** [comment]
Here's a slimmed down version of how we use micro with now v2:

```js
import Joi from "joi";
import { createError, json, run } from "micro";

import auth from "../path/to/auth";

const schema = { email: Joi.string().email() }

export default (req, res) =>
  run(req, res, async request => {
    const payload = await json(request);

    try {
      const { email } = await Joi.validate(payload, schema);
      
      await auth(email)
    } catch (err) {
      if (err.name === "ValidationError") {
        throw createError(400, err.message, err);
      }

      throw createError(500, "Unexpected error", err);
    }

    return "OK";
  });
```

We use `"methods": ["POST"]` in `now.json` to make sure we're only responding to `POST`. You could use any validation method or framework you like (Joi was handy for copy 🍝 ). For an example, you could do something trivial in `auth` (`setTimeout`?) before responding. Micro takes care of status codes and headers which is nice.

**Comment by msweeneydev** [comment]
Closing this issue due to the release of [Node.js Helpers](https://zeit.co/blog/now-node-helpers), this should make things a lot easier for everyone, especially handling request bodies.
