### ISSUE TITLE
How to deploy zerorpc with python and nodejs

### ISSUE THREAD

**Issue by parthi2929** [zeit/now-examples#213]
Hi
Newbie here. I need to use zerorpc for a nodejs web app, which would be invoking python from nodejs for certain operations (deep learning model), but I am not understanding or able to find documentation on how to deploy it in zeit now. . Since both python and nodejs are to be running, I am confused how to start and construct. You could take the simplest zerorpc example [here](https://www.zerorpc.io/) for illustration. Kindly help

**Comment by messa** [comment]
I'm not affiliated with Zeit/Now but I will try to answer this question.

*Now v2* supports only HTTP interface. If you can use HTTP instead of ZeroRPC you would just call the Python HTTP API endpoint from NodeJS using `fetch` (or similar). You can still use msgpack if you need to, just pass it through HTTP instead of ZeroMQ.

In *Now v1* you can run Docker container with whatever you want - you can run both Python and NodeJS processes alongside in one container and do ZeroRPC between them.

**Comment by rauchg** [comment]
@parthi2929 the multi-process use-case with internal communication is unfortunately out of scope (and wasn't properly supported in v1 either)

As @messa pointed out, if you can express your application as a static website and/or functions that act as API endpoints, then ZEIT Now is a great fit for you.
