### ISSUE TITLE
Express with multiple HTTP verbs

### ISSUE THREAD

**Issue by tosbaha** [zeit/now-examples#414]
Express example has a single GET verb with * I tried below but I can't make it work.

TEST1
====

**/api/user.js**

```
app.get('/:slug', (req, res) => {
    res.status(200).json({'First':req.params.slug});
});

app.get('*', (req, res) => {
    res.status(200).json({'hello':'world'});
});
```
https://server/user.js --> HELLO WORLD
https://server/user.js/test --> **ERROR**

TEST2
=====
now.json

```
 "routes": [
        { "src": "/api/user/(.*)", "dest": "/api/user.js/$1" },
      {
        "src": "/",
        "dest": "www/index.html"
      }
    ]
```

https://server/user/test --> **ERROR**

TEST3
=====
now.json

```
 "routes": [
        { "src": "/api/user/(.*)", "dest": "/api/user.js" },
      {
        "src": "/",
        "dest": "www/index.html"
      }
    ]
```

https://server/user/test --> **ERROR**

Could you please document how it is possible to have multiple verbs inside a single file? I don't want to create 5 files with userGet, userPost, userPatch, userDelete,userPut

**Comment by msweeneydev** [comment]
Hey @tosbaha, apologies for the delay in getting back to you here. With the release of our [Node.js Helpers](https://zeit.co/docs/v2/advanced/builders/node-js-now-node/#helpers), it is really easy to do many of the things that Express sought to improve, I definitely recommend you take a look!

If you take a look at some of the new examples, especially [those with serverless functions](https://github.com/zeit/now-examples/tree/master/gatsby-functions), you will see that there is often no need for a `now.json` file anymore.

With regards to your specific question, the recommended method would be to have a separate file for each method, primarily for performance reasons. If you do want to handle multiple different HTTP request methods inside the same serverless function then you could send different responses based on the `request.method`. However, I would still recommend having 5 individual smaller functions inside of `/api/user`.

The [migration](https://zeit.co/guides/migrate-to-zeit-now/) and [upgrade](https://zeit.co/guides/upgrade-to-zero-configuration/) guides are full of information that should be really useful for you. Since we no longer have an Express example (for the reasons mentioned above) I will close this issue. Please feel free to open a thread on [Spectrum](https://spectrum.chat/zeit/general?tab=posts) if you need any further help.
