### ISSUE TITLE
Dev, test, prod in detail

### ISSUE THREAD

**Issue by timweightman** [zeit/now-examples#422]
It'd be great to have an example, or more detailed guide showing how best to set up multiple deployment environments, each with their own environment variables, using the `.env` approach.

I've looked through many of the examples, and read the documentation here: https://zeit.co/docs/v2/development/basics/?query=Now%20dev#development-secrets but can't see anything detailed enough to fully grasp it end-to-end.

One thing I saw mentioned elsewhere in a comment, was having multiple `now.json` files named accordingly `now.dev.json`, and so on for each environment. This seems like _a solution_ but not _the intended solution_ given `now dev` docs explicitly mention `.env` files.

Does the `.env` file only serve the purpose for `now dev`, and if so, do I use `now.json` to configure prod with `@secret-name-x` for each environment variable? And commit that to git? :sweat_smile: 

Or should I be specifying the prod secrets using `-e` on the command line, presumably in a continuous integration pipeline... In that case I guess the "test"/"staging" deployment steps would each use their own secrets that have been created using `now secret ...` and passed along with `-e`.

Thoughts? If I'm on the right track with any of this, I'd be happy to submit a PR.

**Comment by tim-phillips** [comment]
You can/should commit `now.json` and `now.staging.json` files with `@secret-name` and `@secret-name-staging` to version control as long as they have no secrets hardcoded in there. 

I don't personally use `now dev` (the local build process is too slow for my project), but I do know that you can put your dev env vars in `.env` and it will pick them up when it runs. Since `.env` will include your dev secrets, add it to `.gitignore`, and note that `.env` is explicitly ignored always for security reasons when deploying to Now. 

The `-e` flag is just an alternative to declaring env vars in `now.json`. You can do it either way.

**Comment by timweightman** [comment]
Thanks for clarifying `.env` files are ignored for deployments. Understand and agree regarding `.env` files in `.gitignore`.

Definitely not planning to commit hardcoded secrets.

I'll give it a go using the `now.staging.json`. Thanks!

**Comment by mixdev** [comment]
Guess you can use multiple config files using --local-config option and add different env variables in each of the files to switch between production and dev.
